---
name: build

on: [push, pull_request]


jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python-version: ['3.7', '3.8', '3.9', '3.10']
        env:
      # cache busting if requirements haven't changed
            CACHE_EPOCH: 0
        steps:
            - uses: actions/checkout@v4
            - name: Set up Python ${{ matrix.python-version }}
              uses: actions/setup-python@v5
              with:
                  python-version: ${{ matrix.python-version }}

            - name: Install dependencies
              run: |
                  python -m pip install cookiecutter build
                  git config --global user.email "you@example.com"
                  git config --global user.name "Your Name"
                  git config --global init.defaultBranch main

            - name: with neither git nor pre-commit
              run: |
                  GIT=$(which git)
                  sudo chmod -x ${GIT}
                  cookiecutter -v --no-input -f -o /tmp/cookie_python . project_slug=foo1
                  python -m pip install /tmp/cookie_python/foo1
                  python -m pip uninstall -y foo1
                  sudo chmod +x ${GIT}
            - name: with git only
              run: |
                  cookiecutter -v --no-input -f -o /tmp/cookie_python . project_slug=foo2
                  python -m pip install /tmp/cookie_python/foo2
                  python -m pip uninstall -y foo2
            - name: with git and pre-commit
              run: |
                  python -m pip install pre-commit
                  cookiecutter -v --no-input -f -o /tmp/cookie_python . project_slug=foo3
                  python -m pip install /tmp/cookie_python/foo3
                  python -m pip uninstall -y foo3
                  cd /tmp/cookie_python/foo3
                  python -m build
